# Generated by Django 3.2.2 on 2021-05-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Youtube_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
